### PR TITLE
Testing the stored procedure

### PR DESCRIPTION
**Pull request by xsimo**

### CODE REVIEW

**Review by kousen — COMMENTED** [review]
So instead of using a `SimpleJdbcCall`, you used the `createStoredProcedureQuery` method in `EntityManager` to access the stored proc instead. It works, but any particular reason why?

**Comment by xsimo** [comment]
Hi, 
So the reason is because the sakila source code defines a "messy" procedures that spits out a table of existing copies of a film before returning the count(*) of that table. JPA automatic repository is not able to manage that multi result stored procedure and we are getting a message like this : 
`org.springframework.dao.IncorrectResultSizeDataAccessException: Call to stored procedure [film_in_stock] returned multiple results; nested exception is javax.persistence.NonUniqueResultException: Call to stored procedure [film_in_stock] returned multiple results`

So with the javax.persistence.StoredProcedureQuery, we can specify exactly what result we are expecting as an "OUT" mode parameter and the dirver is then ignoring the intermediate result.

**Comment by kousen** [comment]
Thanks for replying. I totally agree that we need to call the stored procedure directly rather than use JPA, though I wasn't sure why I was getting the exception you mentioned (so thanks for that). The thing is, the class you modified already has a method that uses a `SimpleJdbcCall` to do that. Your approach is fine, but I think that's already covered, and without adding in the `EntityManager`. Am I missing something?

**Comment by xsimo** [comment]
Oh, you're right, I did not see those, I had focus on the `Disabled` methods of the `FilmRepositoryTest` class, sorry about that. It is indeed already covered.

**Pull request closed without merging**
